/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Calculator_Display = new javax.swing.JLabel();
        btn_Number_7 = new javax.swing.JButton();
        btn_Number_8 = new javax.swing.JButton();
        btn_Number_9 = new javax.swing.JButton();
        btn_Addition = new javax.swing.JButton();
        btn_Number_4 = new javax.swing.JButton();
        btn_Number_5 = new javax.swing.JButton();
        btn_Number_6 = new javax.swing.JButton();
        btn_Substraction = new javax.swing.JButton();
        btn_Number_1 = new javax.swing.JButton();
        btn_Number_2 = new javax.swing.JButton();
        btn_Number_3 = new javax.swing.JButton();
        btn_Division = new javax.swing.JButton();
        btn_Equal = new javax.swing.JButton();
        btn_Number_0 = new javax.swing.JButton();
        btn_Multiplication = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator ~");

        lbl_Calculator_Display.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_Calculator_Display.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_Calculator_Display.setText("0");
        lbl_Calculator_Display.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbl_Calculator_Display.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        btn_Number_7.setBackground(new java.awt.Color(76, 91, 110));
        btn_Number_7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Number_7.setText("7");
        btn_Number_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_7ActionPerformed(evt);
            }
        });

        btn_Number_8.setBackground(new java.awt.Color(76, 91, 110));
        btn_Number_8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Number_8.setText("8");
        btn_Number_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_8ActionPerformed(evt);
            }
        });

        btn_Number_9.setBackground(new java.awt.Color(76, 91, 110));
        btn_Number_9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Number_9.setText("9");
        btn_Number_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_9ActionPerformed(evt);
            }
        });

        btn_Addition.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Addition.setText("+");

        btn_Number_4.setBackground(new java.awt.Color(76, 91, 110));
        btn_Number_4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Number_4.setText("4");
        btn_Number_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_4ActionPerformed(evt);
            }
        });

        btn_Number_5.setBackground(new java.awt.Color(76, 91, 110));
        btn_Number_5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Number_5.setText("5");
        btn_Number_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_5ActionPerformed(evt);
            }
        });

        btn_Number_6.setBackground(new java.awt.Color(76, 91, 110));
        btn_Number_6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Number_6.setText("6");
        btn_Number_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_6ActionPerformed(evt);
            }
        });

        btn_Substraction.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Substraction.setText("-");

        btn_Number_1.setBackground(new java.awt.Color(76, 91, 110));
        btn_Number_1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Number_1.setText("1");
        btn_Number_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_1ActionPerformed(evt);
            }
        });

        btn_Number_2.setBackground(new java.awt.Color(76, 91, 110));
        btn_Number_2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Number_2.setText("2");
        btn_Number_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_2ActionPerformed(evt);
            }
        });

        btn_Number_3.setBackground(new java.awt.Color(76, 91, 110));
        btn_Number_3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Number_3.setText("3");
        btn_Number_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_3ActionPerformed(evt);
            }
        });

        btn_Division.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Division.setText("/");

        btn_Equal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Equal.setText("=");

        btn_Number_0.setBackground(new java.awt.Color(76, 91, 110));
        btn_Number_0.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Number_0.setText("0");
        btn_Number_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Number_0ActionPerformed(evt);
            }
        });

        btn_Multiplication.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Multiplication.setText("*");

        btn_Clear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Clear.setText("CE");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Calculator_Display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_Number_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(btn_Number_4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(btn_Number_7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btn_Number_5, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                        .addComponent(btn_Number_2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                                    .addComponent(btn_Number_8, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)))
                            .addComponent(btn_Equal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_Number_9, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                .addComponent(btn_Number_6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_Number_0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Number_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Addition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(btn_Substraction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Division, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Multiplication, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Addition, btn_Number_8, btn_Number_9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Calculator_Display, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Clear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Number_7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addComponent(btn_Number_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Number_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Addition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Number_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Number_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Number_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Substraction, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Number_1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btn_Number_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Number_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Equal, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Number_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Multiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Addition, btn_Number_7, btn_Number_8, btn_Number_9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Equal, btn_Number_1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Number_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_1ActionPerformed
        if (lbl_Calculator_Display.getText().length() < 10) {
            if (lbl_Calculator_Display.getText().equals("0")) {
                lbl_Calculator_Display.setText("");
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_1.getText());
            } else {
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_1.getText());
            }
        } else {
            System.out.println("Display Text Full");
        }
    }//GEN-LAST:event_btn_Number_1ActionPerformed

    private void btn_Number_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_2ActionPerformed
        if (lbl_Calculator_Display.getText().length() < 10) {
            if (lbl_Calculator_Display.getText().equals("0")) {
                lbl_Calculator_Display.setText("");
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_2.getText());
            } else {
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_2.getText());
            }
        } else {
            System.out.println("Display Text Full");
        }
    }//GEN-LAST:event_btn_Number_2ActionPerformed

    private void btn_Number_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_3ActionPerformed
        if (lbl_Calculator_Display.getText().length() < 10) {
            if (lbl_Calculator_Display.getText().equals("0")) {
                lbl_Calculator_Display.setText("");
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_3.getText());
            } else {
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_3.getText());
            }
        } else {
            System.out.println("Display Text Full");
        }
    }//GEN-LAST:event_btn_Number_3ActionPerformed

    private void btn_Number_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_4ActionPerformed
        if (lbl_Calculator_Display.getText().length() < 10) {
            if (lbl_Calculator_Display.getText().equals("0")) {
                lbl_Calculator_Display.setText("");
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_4.getText());
            } else {
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_4.getText());
            }
        } else {
            System.out.println("Display Text Full");
        }
    }//GEN-LAST:event_btn_Number_4ActionPerformed

    private void btn_Number_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_5ActionPerformed
        if (lbl_Calculator_Display.getText().length() < 10) {
            if (lbl_Calculator_Display.getText().equals("0")) {
                lbl_Calculator_Display.setText("");
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_5.getText());
            } else {
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_5.getText());
            }
        } else {
            System.out.println("Display Text Full");
        }
    }//GEN-LAST:event_btn_Number_5ActionPerformed

    private void btn_Number_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_6ActionPerformed
        if (lbl_Calculator_Display.getText().length() < 10) {
            if (lbl_Calculator_Display.getText().equals("0")) {
                lbl_Calculator_Display.setText("");
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_6.getText());
            } else {
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_6.getText());
            }
        } else {
            System.out.println("Display Text Full");
        }
    }//GEN-LAST:event_btn_Number_6ActionPerformed

    private void btn_Number_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_7ActionPerformed
        if (lbl_Calculator_Display.getText().length() < 10) {
            if (lbl_Calculator_Display.getText().equals("0")) {
                lbl_Calculator_Display.setText("");
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_7.getText());
            } else {
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_7.getText());
            }
        } else {
            System.out.println("Display Text Full");
        }
    }//GEN-LAST:event_btn_Number_7ActionPerformed

    private void btn_Number_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_8ActionPerformed
        if (lbl_Calculator_Display.getText().length() < 10) {
            if (lbl_Calculator_Display.getText().equals("0")) {
                lbl_Calculator_Display.setText("");
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_8.getText());
            } else {
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_8.getText());
            }
        } else {
            System.out.println("Display Text Full");
        }
    }//GEN-LAST:event_btn_Number_8ActionPerformed

    private void btn_Number_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_9ActionPerformed
        if (lbl_Calculator_Display.getText().length() < 10) {
            if (lbl_Calculator_Display.getText().equals("0")) {
                lbl_Calculator_Display.setText("");
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_9.getText());
            } else {
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_9.getText());
            }
        } else {
            System.out.println("Display Text Full");
        }
    }//GEN-LAST:event_btn_Number_9ActionPerformed

    private void btn_Number_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Number_0ActionPerformed
        if (lbl_Calculator_Display.getText().length() < 10) {
            if (lbl_Calculator_Display.getText().equals("0")) {
                lbl_Calculator_Display.setText("0");
            } else {
                lbl_Calculator_Display.setText(lbl_Calculator_Display.getText() + btn_Number_0.getText());
            }
        } else {
            System.out.println("Display Text Full");
        }
    }//GEN-LAST:event_btn_Number_0ActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        lbl_Calculator_Display.setText(0 + "");
    }//GEN-LAST:event_btn_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Addition;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Division;
    private javax.swing.JButton btn_Equal;
    private javax.swing.JButton btn_Multiplication;
    private javax.swing.JButton btn_Number_0;
    private javax.swing.JButton btn_Number_1;
    private javax.swing.JButton btn_Number_2;
    private javax.swing.JButton btn_Number_3;
    private javax.swing.JButton btn_Number_4;
    private javax.swing.JButton btn_Number_5;
    private javax.swing.JButton btn_Number_6;
    private javax.swing.JButton btn_Number_7;
    private javax.swing.JButton btn_Number_8;
    private javax.swing.JButton btn_Number_9;
    private javax.swing.JButton btn_Substraction;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Calculator_Display;
    // End of variables declaration//GEN-END:variables
}
